version: '3'

services:

    backend:
        build: ./backend
        ports:
            - "8080:8080"
        networks:
            - DemoAppNetwork
    frontend:
        build: ./frontend
        ports:
            - "80:80"
        depends_on:
            - backend
        networks:
            - DemoAppNetwork

networks:
    DemoAppNetwork:
        driver: bridge